#gh-workflow.yml

name: "Github CI/CD Workflow for ReactJS App"

on: [push]

jobs:
  simple_job:
    runs-on: ubuntu-latest
    name: "Simple Job"
    steps:
      - run: echo "Hello, welcome to github actions!"
      - run: echo "Bye" 
