name: "Github CI/CD Workflow for ReactJS App"

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for deployment"
        required: false
        default: "DEV"

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    name: "ubuntu_job"
    steps:
      - name: "Print Welcome"
        run: echo "Hello, welcome to github actions!"
      - name: "Hostname"
        run: hostname
      - name: "Date"
        run: date
      - name: "Config"
        run: uname -a
      - name: "python version"
        run: python3 --version
      - name: "print bye"
        run: echo "bye"
    
  env_var:
    runs-on: ubuntu-latest
    name: "set_env_var"
    steps:
      - run: |
          echo "ENVIRONMENT=${
            { github.event.inputs.environment || (github.ref_name == 'dev' ? 'DEV' : 'PROD') }
          }" >> $GITHUB_ENV
