#gh-workflow.yml

name: "Github CI/CD Workflow for ReactJS App"

on: [push]

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    name: "ubuntu_job"
    steps:
      - name: "Print Welcome"
        run: echo "Hello, welcome to github actions!"
      - name: "Hostname"
        run: echo hostname
      - name: "Date"
        run: echo date
      - name: "Config"
        run: uname -a
      - name: "python version"
        run: python3 --version
      - name: "print bye"
        run: echo "bye"
